### ISSUE TITLE
randomize ordering of students

### ISSUE THREAD

**Issue by timobaumann** [jschildgen/scan_and_mark#3]
the students are always ordered alphabetically. Ordering errors are a well-known problem in exam grading (e.g.: you start with high standards and grow ignorant to small mistakes after a while; a fair result is judged badly after a stellar result; ...). It would be nice if the student list had a shuffle button which one can select before grading a next question as to randomize ordering across all students and questions.

**Comment by jschildgen** [comment]
Good point. But I would not randomize students in the left overview. I would randomize the answers in the right part.

**Comment by jschildgen** [comment]
ORDER BY sin(matno)  
is a simple "solution" to "randomly" sort the students in a deterministic way.

**Comment by jschildgen** [comment]
It's implemented now. The random ordering is not done via SQL, but by Java using the exercise id as the seed.
